# Generated by Django 5.2.1 on 2025-06-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='loaction',
            new_name='location',
        ),
    ]
